import StyledComponentsRegistry from '../lib/registry';
import GlobalProvider from './providers/GlobalProvider';
import MainNavbar from '../components/layout/MainNavbar';
import MobileNavbar from '../components/layout/MobileNavbar';

export const metadata = {
  title: 'make form - 손쉬운 설문 관리',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <GlobalProvider>
            <MainNavbar />
            <MobileNavbar />
            {children}
            {/* <Footer /> */}
          </GlobalProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
