import StyledComponentsRegistry from '../lib/registry';
import GlobalProvider from './GlobalProvider';
import MainNavbar from '../components/layout/MainNavbar';
import MainFooter from '../components/layout/MainFooter';

export const metadata = {
  title: 'make form - 손쉬운 설문 관리',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <StyledComponentsRegistry>
      <html lang="ko">
        <body>
          <GlobalProvider>
            <MainNavbar />
            <section>{children}</section>
            <MainFooter />
          </GlobalProvider>
        </body>
      </html>
    </StyledComponentsRegistry>
  );
}
