import React from 'react';
import StyledComponentsRegistry from '@lib/registry';
import GlobalProvider from '@app/providers/GlobalProvider';
import Navbar from '@components/layout/Navbar';
import MobileNavbar from '@components/layout/MobileNavbar';
import Footer from '@components/layout/Footer';

export const metadata = {
  title: 'make form - 손쉬운 설문 관리',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <GlobalProvider>
            <Navbar />
            <MobileNavbar />
            {children}
            <Footer />
          </GlobalProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
