import StyledComponentsRegistry from '../../lib/registry';
import Providers from './providers';
import MainNavigation from '../../components/layout/main-navigation';

export const metadata = {
  title: 'make form - 손쉬운 설문 관리',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <StyledComponentsRegistry>
      <html lang="ko">
        <body>
          <Providers>
            <MainNavigation />
            <section>{children}</section>
          </Providers>
        </body>
      </html>
    </StyledComponentsRegistry>
  );
}
